services:
  - type: web
    name: qams-global-api
    env: node
    plan: free
    rootDir: server
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: CLIENT_URL
        value: https://your-vercel_app_domain.vercel.app
      - key: MONGODB_URI
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: EMAIL_SERVICE
        value: gmail
